spring:
  config:
    activate:
      on-profile: docker

adapters:
  r2dbc:
    host: postgres-solicitudes
    port: 5432
    database: ${DB_NAME:crediya_autenticacion}
    username: ${DB_USER:crediya_user}
    password: ${DB_PASSWORD:crediya_secure_password_123}

  restconsumer:
    auth-service:
      timeout: 5000
      url: "http://crediya-autenticacion:8080/api/v1"

logging:
  level:
    root: INFO
    org.springframework: INFO
    co.pragma: DEBUG